trigger:
  branches:
    include:
      - '*'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '5.0.301'

stages:
 - stage: 'Provision'
   jobs:
    - job:
      displayName: 'Create Azure resources'
      pool:
        vmImage: 'windows-latest'
      steps:  
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Deploy the arm templates'
          inputs:
            deploymentScope: 'Subscription'
            azureResourceManagerConnection: 'Visual Studio Ultimate with MSDN'
            location: 'Central India'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/scripts/azuredeploy.json'
            deploymentMode: 'Incremental'

 - stage: 'BuildandDeploy'
   jobs:
    - job:
      displayName: 'Build the app'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
          inputs:
            version: '$(dotnetSdkVersion)'

        - task: NuGetToolInstaller@1
          displayName: 'Use nuget'

        - task: DotNetCoreCLI@2
          displayName: 'Restore app dependencies'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Build the app'
          inputs:
            command: 'build'
            arguments: '--no-restore --configuration $(buildConfiguration)'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Package the app'
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(Build.StagingDirectory)'
            zipAfterPublish: True

        - task: AzureWebApp@1
          displayName: 'Deploy the packaged app to Azure web app'
          inputs:
            azureSubscription: 'Visual Studio Ultimate with MSDN'
            appName: 'ekartapi2021'
            package: $(Build.StagingDirectory)/**/*.zip  


