trigger:
  branches:
    include:
      - '*'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.403'

stages:
 - stage: 'Build'
   jobs:
    - job: 'Build' 
      displayName: 'Build the app'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
          inputs:
            version: '$(dotnetSdkVersion)'

        - task: NuGetToolInstaller@1
          displayName: 'Use nuget'

        - task: DotNetCoreCLI@2
          displayName: 'Restore project dependencies'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Build the project - Release'
          inputs:
            command: 'build'
            arguments: '--no-restore --configuration Release'
            projects: '**/*.csproj' 

        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - Release'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
            zipAfterPublish: true      

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: eKart'
          inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)/Release'

        - task: AzureWebApp@1
          displayName: 'Deploy the eKart api'
          inputs:
            azureSubscription: 'Visual Studio Ultimate with MSDN(21490f0c-acc8-4720-bdaa-300c230b5236)'
            appType: 'webApp'
            appName: 'ekartapi2021'
            package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
            deploymentMethod: 'zipDeploy'

