FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine As build-env
WORKDIR /app

COPY eKart.api ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:3.1-alpine

RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

WORKDIR /app
EXPOSE 80

COPY --from=build-env app/out ./
ENTRYPOINT [ "dotnet", "eKart.api.dll" ]